module.exports = {
};

/*
sounds [ { Gender: 'Female',
sounds     Id: 'Joanna',
sounds     LanguageCode: 'en-US',
sounds     LanguageName: 'US English',
sounds     Name: 'Joanna' },
sounds   { Gender: 'Female',
sounds     Id: 'Mizuki',
sounds     LanguageCode: 'ja-JP',
sounds     LanguageName: 'Japanese',
sounds     Name: 'Mizuki' },
sounds   { Gender: 'Female',
sounds     Id: 'Filiz',
sounds     LanguageCode: 'tr-TR',
sounds     LanguageName: 'Turkish',
sounds     Name: 'Filiz' },
sounds   { Gender: 'Female',
sounds     Id: 'Astrid',
sounds     LanguageCode: 'sv-SE',
sounds     LanguageName: 'Swedish',
sounds     Name: 'Astrid' },
sounds   { Gender: 'Male',
sounds     Id: 'Maxim',
sounds     LanguageCode: 'ru-RU',
sounds     LanguageName: 'Russian',
sounds     Name: 'Maxim' },
sounds   { Gender: 'Female',
sounds     Id: 'Tatyana',
sounds     LanguageCode: 'ru-RU',
sounds     LanguageName: 'Russian',
sounds     Name: 'Tatyana' },
sounds   { Gender: 'Female',
sounds     Id: 'Carmen',
sounds     LanguageCode: 'ro-RO',
sounds     LanguageName: 'Romanian',
sounds     Name: 'Carmen' },
sounds   { Gender: 'Female',
sounds     Id: 'Ines',
sounds     LanguageCode: 'pt-PT',
sounds     LanguageName: 'Portuguese',
sounds     Name: 'Inês' },
sounds   { Gender: 'Male',
sounds     Id: 'Cristiano',
sounds     LanguageCode: 'pt-PT',
sounds     LanguageName: 'Portuguese',
sounds     Name: 'Cristiano' },
sounds   { Gender: 'Female',
sounds     Id: 'Vitoria',
sounds     LanguageCode: 'pt-BR',
sounds     LanguageName: 'Brazilian Portuguese',
sounds     Name: 'Vitória' },
sounds   { Gender: 'Male',
sounds     Id: 'Ricardo',
sounds     LanguageCode: 'pt-BR',
sounds     LanguageName: 'Brazilian Portuguese',
sounds     Name: 'Ricardo' },
sounds   { Gender: 'Female',
sounds     Id: 'Maja',
sounds     LanguageCode: 'pl-PL',
sounds     LanguageName: 'Polish',
sounds     Name: 'Maja' },
sounds   { Gender: 'Male',
sounds     Id: 'Jan',
sounds     LanguageCode: 'pl-PL',
sounds     LanguageName: 'Polish',
sounds     Name: 'Jan' },
sounds   { Gender: 'Female',
sounds     Id: 'Ewa',
sounds     LanguageCode: 'pl-PL',
sounds     LanguageName: 'Polish',
sounds     Name: 'Ewa' },
sounds   { Gender: 'Male',
sounds     Id: 'Ruben',
sounds     LanguageCode: 'nl-NL',
sounds     LanguageName: 'Dutch',
sounds     Name: 'Ruben' },
sounds   { Gender: 'Female',
sounds     Id: 'Lotte',
sounds     LanguageCode: 'nl-NL',
sounds     LanguageName: 'Dutch',
sounds     Name: 'Lotte' },
sounds   { Gender: 'Female',
sounds     Id: 'Liv',
sounds     LanguageCode: 'nb-NO',
sounds     LanguageName: 'Norwegian',
sounds     Name: 'Liv' },
sounds   { Gender: 'Male',
sounds     Id: 'Giorgio',
sounds     LanguageCode: 'it-IT',
sounds     LanguageName: 'Italian',
sounds     Name: 'Giorgio' },
sounds   { Gender: 'Female',
sounds     Id: 'Carla',
sounds     LanguageCode: 'it-IT',
sounds     LanguageName: 'Italian',
sounds     Name: 'Carla' },
sounds   { Gender: 'Male',
sounds     Id: 'Karl',
sounds     LanguageCode: 'is-IS',
sounds     LanguageName: 'Icelandic',
sounds     Name: 'Karl' },
sounds   { Gender: 'Female',
sounds     Id: 'Dora',
sounds     LanguageCode: 'is-IS',
sounds     LanguageName: 'Icelandic',
sounds     Name: 'Dóra' },
sounds   { Gender: 'Male',
sounds     Id: 'Mathieu',
sounds     LanguageCode: 'fr-FR',
sounds     LanguageName: 'French',
sounds     Name: 'Mathieu' },
sounds   { Gender: 'Female',
sounds     Id: 'Celine',
sounds     LanguageCode: 'fr-FR',
sounds     LanguageName: 'French',
sounds     Name: 'Céline' },
sounds   { Gender: 'Female',
sounds     Id: 'Chantal',
sounds     LanguageCode: 'fr-CA',
sounds     LanguageName: 'Canadian French',
sounds     Name: 'Chantal' },
sounds   { Gender: 'Female',
sounds     Id: 'Penelope',
sounds     LanguageCode: 'es-US',
sounds     LanguageName: 'US Spanish',
sounds     Name: 'Penélope' },
sounds   { Gender: 'Male',
sounds     Id: 'Miguel',
sounds     LanguageCode: 'es-US',
sounds     LanguageName: 'US Spanish',
sounds     Name: 'Miguel' },
sounds   { Gender: 'Male',
sounds     Id: 'Enrique',
sounds     LanguageCode: 'es-ES',
sounds     LanguageName: 'Castilian Spanish',
sounds     Name: 'Enrique' },
sounds   { Gender: 'Female',
sounds     Id: 'Conchita',
sounds     LanguageCode: 'es-ES',
sounds     LanguageName: 'Castilian Spanish',
sounds     Name: 'Conchita' },
sounds   { Gender: 'Male',
sounds     Id: 'Geraint',
sounds     LanguageCode: 'en-GB-WLS',
sounds     LanguageName: 'Welsh English',
sounds     Name: 'Geraint' },
sounds   { Gender: 'Female',
sounds     Id: 'Salli',
sounds     LanguageCode: 'en-US',
sounds     LanguageName: 'US English',
sounds     Name: 'Salli' },
sounds   { Gender: 'Female',
sounds     Id: 'Kimberly',
sounds     LanguageCode: 'en-US',
sounds     LanguageName: 'US English',
sounds     Name: 'Kimberly' },
sounds   { Gender: 'Female',
sounds     Id: 'Kendra',
sounds     LanguageCode: 'en-US',
sounds     LanguageName: 'US English',
sounds     Name: 'Kendra' },
sounds   { Gender: 'Male',
sounds     Id: 'Justin',
sounds     LanguageCode: 'en-US',
sounds     LanguageName: 'US English',
sounds     Name: 'Justin' },
sounds   { Gender: 'Male',
sounds     Id: 'Joey',
sounds     LanguageCode: 'en-US',
sounds     LanguageName: 'US English',
sounds     Name: 'Joey' },
sounds   { Gender: 'Female',
sounds     Id: 'Ivy',
sounds     LanguageCode: 'en-US',
sounds     LanguageName: 'US English',
sounds     Name: 'Ivy' },
sounds   { Gender: 'Female',
sounds     Id: 'Raveena',
sounds     LanguageCode: 'en-IN',
sounds     LanguageName: 'Indian English',
sounds     Name: 'Raveena' },
sounds   { Gender: 'Female',
sounds     Id: 'Emma',
sounds     LanguageCode: 'en-GB',
sounds     LanguageName: 'British English',
sounds     Name: 'Emma' },
sounds   { Gender: 'Male',
sounds     Id: 'Brian',
sounds     LanguageCode: 'en-GB',
sounds     LanguageName: 'British English',
sounds     Name: 'Brian' },
sounds   { Gender: 'Female',
sounds     Id: 'Amy',
sounds     LanguageCode: 'en-GB',
sounds     LanguageName: 'British English',
sounds     Name: 'Amy' },
sounds   { Gender: 'Male',
sounds     Id: 'Russell',
sounds     LanguageCode: 'en-AU',
sounds     LanguageName: 'Australian English',
sounds     Name: 'Russell' },
sounds   { Gender: 'Female',
sounds     Id: 'Nicole',
sounds     LanguageCode: 'en-AU',
sounds     LanguageName: 'Australian English',
sounds     Name: 'Nicole' },
sounds   { Gender: 'Female',
sounds     Id: 'Marlene',
sounds     LanguageCode: 'de-DE',
sounds     LanguageName: 'German',
sounds     Name: 'Marlene' },
sounds   { Gender: 'Male',
sounds     Id: 'Hans',
sounds     LanguageCode: 'de-DE',
sounds     LanguageName: 'German',
sounds     Name: 'Hans' },
sounds   { Gender: 'Female',
sounds     Id: 'Naja',
sounds     LanguageCode: 'da-DK',
sounds     LanguageName: 'Danish',
sounds     Name: 'Naja' },
sounds   { Gender: 'Male',
sounds     Id: 'Mads',
sounds     LanguageCode: 'da-DK',
sounds     LanguageName: 'Danish',
sounds     Name: 'Mads' },
sounds   { Gender: 'Female',
sounds     Id: 'Gwyneth',
sounds     LanguageCode: 'cy-GB',
sounds     LanguageName: 'Welsh',
sounds     Name: 'Gwyneth' },
sounds   { Gender: 'Male',
sounds     Id: 'Jacek',
sounds     LanguageCode: 'pl-PL',
sounds     LanguageName: 'Polish',
sounds     Name: 'Jacek' } ] +111ms
*/
